### ISSUE TITLE
Unable to generate

### ISSUE THREAD

**Issue by BaoHouxun** [leejet/stable-diffusion.cpp#349]
E:\AI\sd-master-697d000-bin-win-cuda12-x64>sd.exe -m E:\lx\lx\lxaimodels\StableDiffusion-v1.5\deliberate_v2.safetensors -p "a cat."
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 1 CUDA devices:
  Device 0: NVIDIA P104-100, compute capability 6.1, VMM: no
[INFO ] stable-diffusion.cpp:171  - loading model from 'E:\lx\lx\lxaimodels\StableDiffusion-v1.5\deliberate_v2.safetensors'
[INFO ] model.cpp:737  - load E:\lx\lx\lxaimodels\StableDiffusion-v1.5\deliberate_v2.safetensors using safetensors format
[INFO ] stable-diffusion.cpp:194  - Stable Diffusion 1.x
[INFO ] stable-diffusion.cpp:200  - Stable Diffusion weight type: f16

E:\AI\sd-master-697d000-bin-win-cuda12-x64>echo %errorlevel%
-1073741795

**Comment by chinshou** [comment]
It seems stable diffusion cpp failed on RTX 10xx GPU. I have the similar error with 1080ti

**Comment by chinshou** [comment]
I compiled the cuda dll with 12.5 , now it can generate the image with 1080ti in 12s without crash. I guess the problem was caused by the incompatible cuda version I compiled with cuda 12.5 without problem. But the dll provided on the stable diffusion cpp website was compiled with 12.1 or 12.3 I guess.

**Comment by Green-Sky** [comment]
My guess is that no support for your architecture was built into the ci binary. If you build on your system directly, it might add it or make it the sole architecture. Let me see what I can do about that.

**Comment by Green-Sky** [comment]
actually, it should already support your platform.
according to logs it builds
`Using CUDA architectures: 52;61;70;75`
61 should be your 1080ti
https://en.wikipedia.org/wiki/CUDA#GPUs_supported

**Comment by supersonic13** [comment]
I have had this problem for a while. The pre-built binaries never worked and have been getting the same error as mentioned above. Even when compiling locally for my 1060, the Release config also seg faults with the same error but works when I compile to use the Debug config instead of the Release config.
(cmake --build . --config Debug)
(Windows 10, GTX 1060 6GB)

**Comment by Green-Sky** [comment]
Did you use the cudart that is shipped in the release?

**Comment by supersonic13** [comment]
hello @Green-Sky not sure if that question was meant for me. 
But, yes.  I used the shipped cudart dlls in the same directory as the exe, and the program crashes.
I also built with the Release config, and it still crashes.
Works when I build with the Debug config.
Both local builds used  -DSD_CUBLAS=ON flag during Cmake (cmake ../ -DSD_CUBLAS=ON)

**Comment by BaoHouxun** [comment]
I know the reason now, it's because my CPU does not support AVX2.0. It might have been checked during the compilation process. I tried compiling it on my own machine, and everything runs normally.
