### ISSUE TITLE
[Feature Request] taesd VAE (distilled VAE)

### ISSUE THREAD

**Issue by ClashSAN** [leejet/stable-diffusion.cpp#36]
"taesd is tiny, distilled version of a stable diffusion vae."

Image generation results for this vae (showcased on their github) looks nearly identical, maybe having this supported in `stable-diffusion-cpp` this could increase generation speed. 

Github: https://github.com/madebyollin/taesd

**Comment by leejet** [comment]
I've taken a look, and it appears that the VAE model structure differs from the original. I'll find some time to study whether corresponding support needs to be added.

**Comment by leejet** [comment]
By the way, I believe the speed bottleneck is not in the VAE image generation phase but rather in the UNet sampling phase.

**Comment by Green-Sky** [comment]
Now with LCM support, VAE is not ~50% of the time (on my cpu).

**Comment by FSSRepo** [comment]
@leejet The operation that consumes the most memory in the VAE is im2col, up to 1 GB for a 512 x 512 image and 2 GB for a 512 x 768 image. I am considering a way to split the input into chunks and merge them in the output.

**Comment by Green-Sky** [comment]
here they are talking about tiled-decoding https://github.com/madebyollin/taesd/issues/8

**Comment by FSSRepo** [comment]
@leejet I have been working since yesterday on implementing this autoencoder, but for some reason, I'm getting a somewhat over-saturated image. I don't know what I have wrong.

https://github.com/FSSRepo/stable-diffusion.cpp/tree/taesd-impl

# AutoEncoderKL (compute buffer: 1664 MB):

![output](https://github.com/leejet/stable-diffusion.cpp/assets/57494570/fba0d468-4c04-4403-b692-6330bd91892f)

# TinyAutoEncoder (compute buffer: 416 MB):
![output](https://github.com/leejet/stable-diffusion.cpp/assets/57494570/45d7b71b-acd1-4f5a-a394-5c04b9cd9319)

**Comment by Green-Sky** [comment]
@FSSRepo do you know if your model has VAE finetuning?

**Comment by FSSRepo** [comment]
IDK

**Comment by Green-Sky** [comment]
@FSSRepo in any case, good job :) the speed improvement and low memory is insane.

**Comment by FSSRepo** [comment]
> @FSSRepo in any case, good job :) the speed improvement and low memory is insane.

I have not yet checked if there is memory fragmentation since many operations are repeated, so memory usage could be improved
