### ISSUE TITLE
[Bug] width or height can not be 608

### ISSUE THREAD

**Issue by FNsi** [leejet/stable-diffusion.cpp#44]
GGML_Assert ggml.c 5733 a->ne[0] .....

**Comment by leejet** [comment]
The height and width should be multiples of 64. I have updated the prompt for the command line parameters

**Comment by FNsi** [comment]
> The height and width should be multiples of 64. I have updated the prompt for the command line parameters

Nice work🙏

**Comment by dmikey** [comment]
Shouldn't they be multiples of 8?

504x520 is a valid dimension in other SD pipelines.

**Comment by leejet** [comment]
> Shouldn't they be multiples of 8?
> 
> 504x520 is a valid dimension in other SD pipelines.

The sd diffusion process run in the latent space of 1/8 of the width and height. In addition, unet will downsample the middle layer to 1/8 during the operation, so in fact the middle layer size will be 1/64 of width and height, which is why sd.cpp requires width and height to be multiples of 64. If before and after unet sampling, the latent space is expanded and reduced to an integer multiple of 8 by interpolation, the input width and height can be allowed to be an integer multiple of 8, but I have not implemented it yet.

**Comment by rootgrandfather** [comment]
Is there any plan to implement this feature?

**Comment by stduhpf** [comment]
> Is there any plan to implement this feature?

This already works for Flux and SD3 models if you bypass the part that sanitizes the cli arguments. 

For example, if you use the server example (https://github.com/leejet/stable-diffusion.cpp/pull/367) , you can set the width and height in the json payload, and the values aren't being checked. (this causes crashes with Unet-based models btw)

json payload : `{'prompt':""" Two kittens (a black one and a white one) holding together a large sign that says "Flux.cpp works in 720p!", they are on either side of the sign. There are out of focus balls of wool in the background.""",'height':720, 'width':1280, 'seed':42})`
![test](https://github.com/user-attachments/assets/e442a31c-6081-439d-b0f8-188384fba110)
